FROM openfaas/of-watchdog:0.7.7 AS watchdog
FROM node:12-alpine AS build

WORKDIR /home/app/function

# Turn down the verbosity to default level.
ENV NPM_CONFIG_LOGLEVEL warn

COPY package.json ./

RUN npm i

COPY ./ ./

COPY --from=watchdog /fwatchdog /usr/bin/fwatchdog
RUN chmod +x /usr/bin/fwatchdog

# Add non root user
RUN addgroup -S app && adduser app -S -G app
RUN chown app /home/app
USER app

ENV mode="static"
# Served using cra-build-watch
ENV static_path="/home/app/function/build"

ENV exec_timeout="10s"
ENV write_timeout="11s"
ENV read_timeout="11s"

HEALTHCHECK --interval=5s CMD [ -e /tmp/.lock ] || exit 1

CMD ["fwatchdog"]
