= Bitcoin Studio website - client repository

* Code
** Based on Create-React-App
** Typescript
** ReactJS (function components, React Hooks)

* Styling
** Sass pre-processor
** CSS Grid for the layout


== Hosting

MicroService function hosted on OpenFaaS. +
Based on OpenFaaS Dockerfile template, serving the app with Nginx: +
https://github.com/alexellis/static-site-template


== Running the prod locally

.In one tab
 kubectl port-forward svc/gateway -n openfaas 8080:8080

.In a other tab
 faas up


== Developing with Okteto

.Make sure the prod image is deployed
 faas up

.Build a dev image with NodeJS and Nginx into the local Docker library
 DEV=dev faas build

.Push that image to Okteto container registry
 DEV=dev faas push

 cd function

.Sync local source code with remote using dev image
 okteto up

=== Inside Okteto console

.Run OpenFaaS watchdog in the background
 fwatchdog &

.Press Enter

.Install dependencies
 cd function

 npm ci

.Run build on file change
 npm run watch


=== Shortcomings

==== No Hot Reloading

For now, create-react-app doesn't give to possibility to write webpack-dev-server output to disk (see https://github.com/facebook/create-react-app/pull/6144[this thread]).
We are forced to use an external tool. This project uses https://github.com/Nargonath/cra-build-watch[cra-build-watch].
It works fine but doesn't allow for hot reloading.

==== Service Worker

The service worker may cause issues. If you activate it, make sure to develop the app in incognito window on Chrome or similar.



== Differences in Dev/Prod Environments

=== Development - 127.0.0.1 and Okteto Serving From SubPath

.Environment variables
 PUBLIC_URL=/function/bitcoin-studio-client
 REACT_APP_SEND_EMAIL_URL=https://openfaas-ingress-janaka-steph.cloud.okteto.net/function/bitcoin-studio-client/api/send-email

.Manifest.json
 start_url = "/function/bitcoin-studio-client/index.html"

.Nginx
 /api/email points to dev server

.Deploy command
 faas up -f stack-dev.yml -n janaka-steph


=== Production - Custom Domain (using FunctionIngress CRD)

.Environment variables
 No PUBLIC_URL
 REACT_APP_SEND_EMAIL_URL=/api/send-email

.Manifest.json
 start_url = "."

.Nginx
 /api/email points to prod server

