version: 1.0
provider:
  name: openfaas
  gateway: https://openfaas.rogue-paprika.top
  #gateway: https://openfaas-ingress-janaka-steph.cloud.okteto.net
  #gateway: http://127.0.0.1:8080

functions:
  bitcoin-studio-client:
    lang: dockerfile${DEV}
    handler: ./function
    image: janakasteph/bitcoin-studio-client:${DEV:-latest}
    #image: registry.cloud.okteto.net/janaka-steph/bitcoin-studio-client:${DEV:-latest}
    #environment:
    #  write_debug: true